before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows # Does not compile for Arm Windows due to go-ole https://github.com/shirou/gopsutil/issues/916
        goarch: arm64
    no_unique_dist_dir: true
    binary: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  # Define the GitLab release configuration
  gitlab:
    owner: TitanInd/proxy
    name: proxy-router
    token:
      # Define your GitLab API token here
      # You can generate a token in your GitLab account settings
      secure: "{{.Env.CI_TAG_PUSH_TOKEN}}""
    # Define the release notes format
    release_name_template: "{{.ProjectName}}-{{.Tag}}"
    release_description_template: "Release {{.Tag}}"
