with-expecter: true
filename: "{{.InterfaceName | snakecase}}_mock.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}Mock"
outpkg: "mocks"
packages:
  gitlab.com/TitanInd/proxy/proxy-router-v3/internal/repositories/contracts:
    interfaces:
      EthereumClient: