services:
  proxy-router:
    build:
      context: .
      args:
        COMMIT: ${COMMIT:-unknown}
        TAG_NAME: ${TAG_NAME:-latest}
    image: proxy-router:${TAG_NAME}
    env_file:
      - .env
    ports:
      - 8081:8081
      - 3333:3333